version: '3.6'

services:
  superbara:
    image: mattipaksula/superbara
    environment:
      - SUPERBARA_FRONTEND=noninteractive
      - CHROME_URL=http://chrome:4444/wd/hub
    volumes:
      - ./e2e:/e2e
    depends_on:
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug:3.11.0-californium
    ports:
      - 15900:5900
      - 14444:4444
    shm_size: 2g
